Jigsaw-Code/outline-releases

client/latest.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.0.1
=> update windows client to v1.0.1, add auto-update config

client/latest.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.0.3
=> update windows client to v1.0.3

manager/latest-linux.yml, manager/latest-mac.json, manager/latest-mac.yml
https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.0.7
=> update manager to v1.0.7, add auto-update info

client/latest.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.0.4
=> update windows client to v1.0.4

manager/latest-linux.yml, manager/latest-mac.json, manager/latest-mac.yml, manager/latest.yml
Rolls out the release to 10% of users in all platforms.
=> Release Outline Manager v1.1.1

manager/latest-linux.yml, manager/latest-mac.json, manager/latest-mac.yml, manager/latest.yml
https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.1.2
=> release server manager 1.1.2

client/latest.yml
* Updated Shadowsocks to v3.2.0.
* Added system tray support.
=> Release Windows client v1.1.2

manager.sh, release_manager.sh
Just a quick thing because I got tired of doing this manually. I just used it to generate:
https://github.com/Jigsaw-Code/outline-releases/pull/72
Helps a little with:
https://github.com/Jigsaw-Code/outline-releases/issues/18
=> add a script to update server manager files

manager/latest-linux.yml, manager/latest-mac.yml, manager/latest.yml
https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.1.9
=> release server manager v1.1.9

manager/README.md
Copies the latest manager release (v1.1.9) to `manager/stable/`.
=> Create manager stable release

manager/latest-linux.yml, manager/latest-mac.yml, manager/latest.yml
Should only be merged after [outline-website/#99](https://github.com/Jigsaw-Code/outline-website/pull/99) and #89 are merged.
=> Release Outline Manager v1.2.0 to 20%

manager/latest-linux.yml, manager/latest-mac.yml, manager/latest.yml
=> Release Outline Manager v1.2.1

manager/latest-linux.yml, manager/latest-mac.yml, manager/latest.yml
https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.2.2
=> release server manager v1.2.2

client/latest.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.24
=> release windows client v1.2.24

release_linux_client.sh
There's obviously a lot of duplicated code now in these three scripts but I'd like to tackle that at some later stage.
=> add a script to update the linux client

client/latest-linux.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/linux-v1.0.3
=> release linux client v1.0.3

client/latest.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.26
=> release windows client v1.2.26

client/latest-linux.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/linux-v1.0.5
=> release linux client v1.0.5

client/latest.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.27
=> release windows client v1.2.27

client/latest.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.29
=> release windows client v1.2.29

client/latest.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.30
=> release windows client v1.2.30 to 20%

client/latest.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.31
=> release windows client v1.2.31

client/latest-linux.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/linux-v1.0.6
=> release linux client v1.0.6

manager/latest-linux.yml, manager/latest-mac.yml, manager/latest.yml
=> Release Outline Manager v1.2.3

client/beta/beta-linux.yml, client/beta/beta.yml, client/stable/latest-linux.yml, client/stable/latest.yml
The release scripts will be updated in a future PR.  I want to get this up and running so I can finish testing the requests metrics pipeline.
=> Create a beta channel release and add update info files to client/stable

manager/latest-linux.yml, manager/latest-mac.yml, manager/latest.yml
https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.3.0
=> Release Outline Manager v1.3.0

manager/latest-linux.yml, manager/latest-mac.yml, manager/latest.yml
To be released April 29th 2020.
=> Release Outline Manager v1.5.0

manager/latest-linux.yml, manager/latest-mac.yml, manager/latest.yml
[Release notes](https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.5.1).
=> Release Outline Manager v1.5.1

client/latest.yml
[windows-v1.4.0](https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.4.0)
=> Release Windows client v1.4.0

manager/latest-linux.yml, manager/latest-mac.yml, manager/latest.yml
[Release notes](https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.6.0)
=> Release Outline Manager v1.6.0

manager/latest-linux.yml, manager/latest-mac.yml, manager/latest.yml
[Release notes](https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.6.1)
=> Release Outline Manager v1.6.1

client/latest.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.5.0
=> Release windows client v1.5.0

client/latest-linux.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/linux-v1.3.0
=> Release Linux client v1.3.0

manager/latest-linux.yml, manager/latest-mac.yml, manager/latest.yml
https://github.com/Jigsaw-Code/outline-server/releases/tag/v1.8.0
=> Release Outline Manager v1.8.0

client/latest-linux.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/linux-v1.4.0
=> Release linux client v1.4.0

client/latest.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.6.0
=> Release windows client v1.6.0

.github/workflows/upload_windows_client_to_s3.yml
Fixes an incorrect file extension for the Windows client binary.
=> Fix windows client binary file extension

client/latest.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.7.0
=> release windows client v1.7.0

client/latest.yml
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.7.1
=> Release windows client v1.7.1

client/latest-linux.yml, client/stable/latest-linux.yml
* chore(ui): convert server-connection-indicator to lit by @daniellacosse in https://github.com/Jigsaw-Code/outline-client/pull/1273
* fix(ui): explicit width and height for expanded server indicator by @daniellacosse in https://github.com/Jigsaw-Code/outline-client/pull/1279
* fix(ui): missed an indicator by @daniellacosse in https://github.com/Jigsaw-Code/outline-client/pull/1285
* fix(ui): fix server empty state by @daniellacosse in https://github.com/Jigsaw-Code/outline-client/pull/1290
* 💊 fix(electron): fix wrong connection status when error is thrown during connect by @jyyi1 in https://github.com/Jigsaw-Code/outline-client/pull/1286
* fix(www): restore initial indicator appearance by @daniellacosse in https://github.com/Jigsaw-Code/outline-client/pull/1303
**Full Changelog**: …
=> Release linux client v1.7.0

manager/latest-linux.yml, manager/latest.yml
We updated the DigitalOcean price from $5 to $6.
=> release server manager v1.10.1

manager/latest-linux.yml, manager/latest-mac.yml, manager/latest.yml
=> release Outline Manager v1.11.0

manager/latest-linux.yml, manager/latest-mac.yml, manager/latest.yml
**Changelog**
- [invite flow improvement](https://github.com/Jigsaw-Code/outline-server/pull/1198)
=> Release Outline Manager v1.13.0

client/latest.yml, client/stable/latest.yml
This release will fix the connection issue for Outline Client on Windows: https://github.com/Jigsaw-Code/outline-client/issues/1535
=> Release Outline Client hotfix 1.9.1 for Windows

client/latest-linux.yml, client/latest.yml, client/stable/latest-linux.yml, client/stable/latest.yml
- temporarily remove client feedback view on Windows and Linux
- fix ssconf:// deeplinking on ios
- support more languages
- fix connection issue for UDP protocol
=> deploy: release client v1.10.0
